name: Maven-Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    types: [ opened, synchronize, reopened ]

jobs:
  Maven-Tests:
    name: Maven-Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      # - name: Wait for Docker daemon
      #   env:
      #     DOCKER_HOST: tcp://localhost:2375
      #   run: |
      #     for i in {1..30}; do
      #       if docker info > /dev/null 2>&1; then
      #         echo "Docker API is ready"
      #         exit 0
      #       fi
      #       echo "Waiting for Docker API..."
      #       sleep 2
      #     done
      #     echo "Timed out waiting for Docker API" >&2
      #     exit 1

      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B test --file pom.xml
