name: Maven-Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    types: [ opened, synchronize, reopened ]

jobs:
  Maven-Tests:
    name: Maven-Tests
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B test --file pom.xml
